apiVersion: apps/v1
kind: Deployment
metadata:
  name: App
spec:
  selector:
    matchLabels:
      app: app
  replicas: 6
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: php-app
        image: bhatia53/proj2
        ports:
        - containerPort: 80
          name: web-port

apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    apps: app
spec:
  type: NodePort
  ports:
  - name: tcp-31081-5000
    nodePort: 32000
    port: 80
    protocol: TCP
  selector:
    app: app
